README.md
=> readme: bitcoinui

LDKNodeMonday/Bitcoin/View Model/BitcoinViewModel.swift, LDKNodeMonday/Bitcoin/View/BitcoinView.swift, LDKNodeMonday/Extensions/UInt64+Extensions.swift
=> ui: balance styling

LDKNodeMonday.xcodeproj/project.pbxproj, LDKNodeMonday/Bitcoin/View/AddressView.swift, LDKNodeMonday/Bitcoin/View/QRCodeViewBitcoin.swift, LDKNodeMonday/Extensions/View+Extensions.swift, LDKNodeMonday/Lightning/Receive/View/QRCodeViewLightning.swift, LDKNodeMonday/Lightning/Receive/View/ReceiveView.swift
=> ui: fidgetqrcodeview

LDKNodeMonday.xcodeproj/project.pbxproj, LDKNodeMonday.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LDKNodeMonday/Extensions/ChannelDetails+Extensions.swift, LDKNodeMonday/Service/Lightning Service/LightningNodeService.swift, LDKNodeMonday/Utilities/MondayError.swift, LDKNodeMonday/View Model/Lightning/Channel/ChannelAddViewModel.swift, LDKNodeMonday/View Model/Lightning/Receive/ReceiveViewModel.swift, LDKNodeMonday/View Model/Lightning/Send/SendConfirmationViewModel.swift, LDKNodeMonday/View/Lightning/Channel/ChannelDetailView.swift
=> spm: ldk-node 0.2.0

.github/workflows/ios.yml
=> ci: xcode 15.0.1 / iphone 15 / ios 17.0.1

LDKNodeMonday.xcodeproj/project.pbxproj, LDKNodeMonday.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
=> spm: bitcoinui 1.0.3

LDKNodeMonday/View/Bitcoin/BitcoinView.swift
=> ui: spendable

LDKNodeMonday/View/Lightning/Channel/ChannelDetailView.swift
=> ui: close channel alert

LDKNodeMonday/View/Lightning/NodeID/NodeIDView.swift
=> ui: node view alerts

LDKNodeMonday/Info.plist
=> misc: remove ats

LDKNodeMonday/View/Lightning/Channel/PaymentsListView.swift
=> ui: payment list format

LDKNodeMonday/View/Lightning/Send/SendConfirmationView.swift
=> ui: send confirmation

LDKNodeMonday/View/Lightning/Channel/ChannelDetailView.swift, LDKNodeMonday/View/Lightning/Send/SendConfirmationView.swift
=> ui: channel detail

LDKNodeMonday/View/Lightning/Channel/ChannelsListView.swift
=> ui: alias none

.github/workflows/ios.yml
=> ci: mac-os14

LDKNodeMonday/Service/Lightning Service/LightningNodeService.swift
=> misc: trace logs

LDKNodeMonday.xcodeproj/project.pbxproj, LDKNodeMonday/View/Bitcoin/AddressView.swift, LDKNodeMonday/View/Bitcoin/BitcoinView.swift, LDKNodeMonday/View/Bitcoin/SendBitcoinView.swift, LDKNodeMonday/View/Home/StartView.swift, LDKNodeMonday/View/Lightning/Channel/ChannelAddView.swift, LDKNodeMonday/View/Lightning/Channel/ChannelsListView.swift, LDKNodeMonday/View/Lightning/Channel/PaymentsListView.swift, LDKNodeMonday/View/Lightning/NodeID/NodeIDView.swift, LDKNodeMonday/View/Lightning/Peer/DisconnectView.swift, LDKNodeMonday/View/Lightning/Peer/PeerView.swift, LDKNodeMonday/View/Lightning/Receive/ReceiveView.swift, LDKNodeMonday/View/Lightning/Send/SendView.swift
=> ui: support larger system font

LDKNodeMonday/View Model/Bitcoin/SendBitcoinViewModel.swift, LDKNodeMonday/View Model/Lightning/Channel/ChannelAddViewModel.swift, LDKNodeMonday/View Model/Lightning/Peer/PeerViewModel.swift, LDKNodeMonday/View Model/Lightning/Receive/ReceiveViewModel.swift, LDKNodeMonday/View Model/Lightning/Send/SendViewModel.swift, LDKNodeMonday/View/Bitcoin/SendBitcoinView.swift
=> ui: textfield trim whitespace and new lines

LDKNodeMonday/View Model/Bitcoin/SendBitcoinViewModel.swift, LDKNodeMonday/View Model/Lightning/Channel/ChannelAddViewModel.swift, LDKNodeMonday/View Model/Lightning/Peer/PeerViewModel.swift, LDKNodeMonday/View Model/Lightning/Receive/ReceiveViewModel.swift, LDKNodeMonday/View Model/Lightning/Send/SendViewModel.swift, LDKNodeMonday/View/Bitcoin/AddressView.swift, LDKNodeMonday/View/Bitcoin/BitcoinView.swift, LDKNodeMonday/View/Bitcoin/SendBitcoinView.swift, LDKNodeMonday/View/Home/OnboardingView.swift, LDKNodeMonday/View/Home/StartView.swift, LDKNodeMonday/View/Home/TabHomeView.swift, LDKNodeMonday/View/Lightning/Channel/ChannelAddView.swift, LDKNodeMonday/View/Lightning/Channel/ChannelDetailView.swift, LDKNodeMonday/View/Lightning/Channel/ChannelsListView.swift, LDKNodeMonday/View/Lightning/Channel/PaymentsListView.swift, LDKNodeMonday/View/Lightning/NodeID/NodeIDView.swift, LDKNodeMonday/View/Lightning/Peer/DisconnectView.swift, LDKNodeMonday/View/Lightning/Peer/PeerView.swift, LDKNodeMonday/View/Lightning/Peer/PeersListView.swift, LDKNodeMonday/View/Lightning/Receive/ReceiveView.swift, LDKNodeMonday/View/Lightning/Send/SendConfirmationView.swift, LDKNodeMonday/View/Lightning/Send/SendView.swift
=> ui: add accessibility large previews

LDKNodeMonday/Service/Lightning Service/LightningNodeService.swift, LDKNodeMonday/Utilities/Constants.swift
=> misc: esplora mainnet

LDKNodeMonday/View/Bitcoin/SendBitcoinView.swift, LDKNodeMonday/View/Home/OnboardingView.swift, LDKNodeMonday/View/Lightning/Channel/ChannelAddView.swift, LDKNodeMonday/View/Lightning/Peer/PeerView.swift, LDKNodeMonday/View/Lightning/Receive/ReceiveView.swift, LDKNodeMonday/View/Lightning/Send/SendView.swift
=> ui: textfield submit label

LDKNodeMonday/View/Lightning/Channel/ChannelsListView.swift
=> ui: lightning receive large

LDKNodeMonday/View Model/Lightning/NodeID/NodeIDViewModel.swift, LDKNodeMonday/View/Lightning/NodeID/NodeIDView.swift
=> feat: node id network

LDKNodeMonday/View/Lightning/Channel/ChannelAddView.swift
=> ui: add channel node id text size

LDKNodeMonday/View/Bitcoin/SendBitcoinView.swift, LDKNodeMonday/View/Lightning/Send/SendView.swift
=> ui: send placeholder text

LDKNodeMonday/Service/Lightning Service/LightningNodeService.swift, LDKNodeMonday/View Model/Profile/NodeIDViewModel.swift, LDKNodeMonday/View/Profile/NodeIDView.swift
=> feat: node status

LDKNodeMonday/Extensions/String+Extensions.swift, LDKNodeMonday/Service/Lightning Service/LightningNodeService.swift, LDKNodeMonday/View Model/Home/AmountViewModel.swift, LDKNodeMonday/View/Home/Send/AmountView.swift
=> feat: send specific amount

LDKNodeMonday/View/Home/BitcoinView.swift
=> ui: sign format padding

LDKNodeMonday.xcodeproj/project.pbxproj, LDKNodeMonday/Model/ReceiveOption.swift, LDKNodeMonday/Service/Lightning Service/LightningNodeService.swift, LDKNodeMonday/View Model/Home/Receive/Bolt12InvoiceViewModel.swift, LDKNodeMonday/View/Home/Receive/Bolt12InvoiceView.swift, LDKNodeMonday/View/Home/Receive/ReceiveView.swift
=> wip: bolt 12

LDKNodeMonday/Service/Lightning Service/LightningNodeService.swift
=> chore: use default config

LDKNodeMonday/Service/Lightning Service/LightningNodeService.swift, LDKNodeMonday/View/Home/Send/AmountView.swift, LDKNodeMonday/View/Profile/Channel/ChannelAddView.swift
=> chore: handle remaining error states

LDKNodeMonday.xcodeproj/project.pbxproj, LDKNodeMonday.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LDKNodeMonday/View Model/Home/OnboardingViewModel.swift, LDKNodeMonday/View/Home/OnboardingView.swift, LDKNodeMonday/View/Profile/Danger/SeedView.swift
=> spm: bitcoinui main

LDKNodeMonday.xcodeproj/project.pbxproj, LDKNodeMonday.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LDKNodeMonday/View/Home/BitcoinView.swift, LDKNodeMonday/View/Profile/Channel/ChannelsListView.swift
=> spm: bitcoinui 1.0.4

LDKNodeMonday/Utilities/Constants.swift
=> feat: add olympus lsp

LDKNodeMonday.xcodeproj/project.pbxproj, LDKNodeMonday.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LDKNodeMonday/View/Home/OnboardingView.swift, LDKNodeMonday/View/Profile/Danger/SeedView.swift
=> ui: seedphraseview paging

LDKNodeMonday.xcodeproj/project.pbxproj, LDKNodeMonday.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
=> spm: bitcoinui 1.0.6

LDKNodeMonday/View/Home/BitcoinView.swift
=> ui: main view sf symbols

LDKNodeMonday/View Model/Home/Receive/BIP21ViewModel.swift, LDKNodeMonday/View Model/Home/Receive/JITInvoiceViewModel.swift, LDKNodeMonday/View/Home/Receive/BIP21View.swift, LDKNodeMonday/View/Home/Receive/JITInvoiceView.swift
=> feat: remove clear invoice

LDKNodeMonday/View/Home/Send/AddressView.swift
=> ui: paste button

LDKNodeMonday/View/Home/BitcoinView.swift, LDKNodeMonday/View/Home/OnboardingView.swift, LDKNodeMonday/View/Home/Payments/PaymentsListView.swift, LDKNodeMonday/View/Home/Payments/PaymentsView.swift, LDKNodeMonday/View/Home/Send/AddressView.swift, LDKNodeMonday/View/Home/StartView.swift, LDKNodeMonday/View/Profile/Channel/ChannelAddView.swift, LDKNodeMonday/View/Profile/Channel/ChannelDetailView.swift, LDKNodeMonday/View/Profile/Channel/ChannelsListView.swift, LDKNodeMonday/View/Profile/NodeIDView.swift, LDKNodeMonday/View/Profile/Peers/DisconnectView.swift, LDKNodeMonday/View/Profile/Peers/PeerView.swift, LDKNodeMonday/View/Profile/Peers/PeersListView.swift
=> ui: previews

README.md
=> readme: screenshot dimensions

LDKNodeMonday/App/LDKNodeMondayApp.swift, LDKNodeMonday/Extensions/PaymentKind+Extensions.swift, LDKNodeMonday/Service/Lightning Service/LightningServiceError.swift, LDKNodeMonday/View Model/Profile/Channel/ChannelAddViewModel.swift, LDKNodeMonday/View/Home/BitcoinView.swift, LDKNodeMonday/View/Home/OnboardingView.swift, LDKNodeMonday/View/Home/Payments/PaymentsListView.swift, LDKNodeMonday/View/Home/Payments/PaymentsView.swift, LDKNodeMonday/View/Home/Receive/BIP21View.swift, LDKNodeMonday/View/Home/Receive/JITInvoiceView.swift, LDKNodeMonday/View/Home/Receive/ReceiveView.swift, LDKNodeMonday/View/Home/Send/AmountView.swift, LDKNodeMonday/View/Home/StartView.swift, LDKNodeMonday/View/Profile/Channel/ChannelAddView.swift, LDKNodeMonday/View/Profile/Channel/ChannelDetailView.swift, LDKNodeMonday/View/Profile/Channel/ChannelsListView.swift, LDKNodeMonday/View/Profile/Danger/SeedView.swift, LDKNodeMonday/View/Profile/NodeIDView.swift, LDKNodeMonday/View/Profile/Peers/DisconnectView.swift, LDKNodeMonday/View/Profile/Peers/PeerView.swift, LDKNodeMonday/View/Profile/Peers/PeersListView.swift
=> fix: nodeidview delete seed

LDKNodeMonday/Utilities/Constants.swift
=> refactor: order or signet

LDKNodeMonday/View/Profile/Channel/ChannelsListView.swift, LDKNodeMonday/View/Profile/NodeIDView.swift
=> refactor: rename channels list view

LDKNodeMonday.xcodeproj/project.pbxproj, LDKNodeMonday.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LDKNodeMonday/Extensions/Event+Extensions.swift, LDKNodeMonday/Service/Lightning Service/LightningNodeService.swift, LDKNodeMonday/Service/Lightning Service/LightningServiceError.swift, LDKNodeMonday/View/Profile/Channel/ChannelDetailView.swift
https://github.com/lightningdevkit/ldk-node/releases/tag/v0.4.0
=> spm: ldk-node 0.4.0

LDKNodeMonday.xcodeproj/project.pbxproj, LDKNodeMonday.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
https://github.com/lightningdevkit/ldk-node/pull/391
=> spm: ldk-node 0.4.2

LDKNodeMonday/Utilities/Constants.swift
=> fix: snapshot signet

LDKNodeMonday.xcodeproj/project.pbxproj
https://github.com/lightningdevkit/ldk-node/releases/tag/v0.4.3
=> spm: ldk node 0.4.3

LDKNodeMonday/View/Home/NetworkSettingsView.swift
This is a bugfix to address issues with switching network and server.
Not sure when this regression happened.
Can look deeper into this later as it seems we could simplify this logic.
=> bugfix: networksettings

LDKNodeMonday/View/Settings/SettingsView.swift
Give people a hint to where they can find helpful logs
=> feat: settings view hint for logs

LDKNodeMonday/View/Settings/SettingsView.swift
Helpful link if someone wants to open an issue.
=> feat: settings view link to issue

LDKNodeMonday/Service/Lightning Service/LightningNodeService.swift
=> fix: issue-198

LDKNodeMonday/View Model/Home/Send/SendViewModel.swift
=> (draft) issue-183

LDKNodeMonday.xcodeproj/project.pbxproj, LDKNodeMonday.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LDKNodeMonday/App/WalletClient.swift, LDKNodeMonday/Extensions/UInt64+Extensions.swift, LDKNodeMonday/Service/Lightning Service/LightningNodeService.swift, LDKNodeMonday/View Model/Home/Receive/ReceiveViewModel.swift
=> deps: ldk node 0.6.2
